### ISSUE TITLE
Figure out weird standata issue

### ISSUE THREAD

**Issue by jsocolar** [jsocolar/flocker#17]
Simon reports:
I get the error  Error: No method asJSON S3 class: standata at the sampling stage, which is the same issue as outlined here: https://discourse.mc-stan.org/t/how-to-convert-standata-to-json/17020. No idea why you don't get this issue when you run it, but I have to fix it to get anything downstream to work. The solution is just to convert the S3 list generated by brms::make_standata to a standard list, which I've done, but I then get the following error at the model sampling stage:
Chain 1 Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int (in 'C:/Users/smills2/AppData/Local/Temp/Rtmpei13q7/model-3670682149c4.stan', line 5, column 2 to column 17)
Warning: Chain 1 finished unexpectedly!

So far I cannot reproduce.

**Comment by jsocolar** [comment]
Ok @SimonCMills got it!  This is an issue that is fixed in the development version of brms.  Reverting to the CRAN version allowed me to reproduce, re-updating to the development version fixed.

**Comment by jsocolar** [comment]
Updated DESCRIPTION to brms >= 2.15.9 in https://github.com/jsocolar/flocker/commit/d27a21226b7cec7d2eb91fac1553a6de621e27de. @SimonCMills can you confirm that the fix works for you, and if so I'll close this one.

**Comment by jsocolar** [comment]
The fix being `remotes::install_github("paul-buerkner/brms")`

**Comment by SimonCMills** [comment]
It runs! Issue resolved.
