### ISSUE TITLE
rename function flocker::flocker

### ISSUE THREAD

**Issue by jsocolar** [jsocolar/flocker#20]
I'm not deadset on this, but I think we should consider renaming our main function to avoid confusion in the documentation for when we mean `flocker` the package verus `flocker::flocker` the function.  Open to suggestions.

**Comment by jsocolar** [comment]
@SimonCMills opinions here?

**Comment by SimonCMills** [comment]
Yeah, agree that a different name would be an improvement. No strong opinions about the name, perhaps `flock()` or `flocker_run()` (or `flocker_something()`)?

**Comment by jsocolar** [comment]
I'll attempt a complete re-factor this week to support native `brms` implementation.  In doin this, I'll change to `flock`

**Comment by jsocolar** [comment]
Renamed in the custom_family refactor to `flocker::flock`
