### ISSUE TITLE
Uninformative error message when specifying priors

### ISSUE THREAD

**Issue by SimonCMills** [jsocolar/flocker#42]
If the user provides priors on parameter classes (e.g. `set_priors(normal(0,1), class="b"`, `set_priors(normal(0,1), class="sd")`), but these parameter classes *only* exist in the occupancy component (e.g. `f_occ = ~ 1 + covariate` and `f_det ~ 1`, or `f_occ = ~ 1 + (1|group)` and `f_det = ~1`), they get the uninformative error of, e.g.:

```
Error: The following priors do not correspond to any model parameter: 
b ~ normal(0, 1)
```
or
```
Error: The following priors do not correspond to any model parameter: 
sd ~ normal(0, 1)
```

when the parameters do exist, it's just that they aren't in the detection component. A quick solution is to specify that the priors only correspond to the occupancy component by, e.g. `set_priors(normal(0,1), class="b", dpar="occ")`, but not sure what the longer-term fix should be. Most simply it could just be a warning message in the priors section of the vignette, most complicated (but best) would be to check that, if priors are specified on particular classes that only exist in the occupancy component then `flock` either (a) throws an informative error message or (b) just silently updates the priors object. Fwiw, I think (b) is probably best if it's not a nightmare to implement. I can have a stab at it in the next few days.

**Comment by jsocolar** [comment]
We could require a `flockerprior` argument to `flock` that defaults to something corresponding to the default `brms` prior, and thereby *force* people to use our own functions to create their priors.  Not sure whether forcing the brms-savvy into this additional layer of abstraction from the underlying `brms` model is a great idea though...

**Comment by jsocolar** [comment]
Upon further reflection, I think we want to trust Paul to handle and improve upon priors better/faster than we will, and since there's no need to force users to do something different from what brms does natively, we should just rely on the native brms stuff.  However, I do think that this would be a useful issue to file against brms.  @SimonCMills , want to do that?  I guess you have some clout over there now that you're a contributor and all :)

**Comment by SimonCMills** [comment]
Done: https://github.com/paul-buerkner/brms/issues/1490. 

Will update you on any developments.
